### PR TITLE
Please check if my commits fixed the issue I submit.

### PR DESCRIPTION
**Pull request by Magicloud**
I blocked timer signals when checkLEe call the action.

### CODE REVIEW

**Comment by jgoerzen** [comment]
Hi,

Thank you for the addition, but I am not sure if this is the correct approach; will it still work on non-Unix platforms, for instance?

**Comment by Magicloud** [comment]
I have not thought about that.... The signal block around ldap invoke should be correct for at least *nix. On non-Unix, I have no idea.... Maybe a conditional compile? I am not familiar with it.

**Comment by ezyang** [comment]
The other thing to note is that if EINTR is in some sense properly handled by LDAP, what we should do instead is retry on EINTR, ala throwErrnoIfRetry

**Comment by Magicloud** [comment]
About the EINTR, I do not think it was handled by LDAP, but ghc run-time. According to simonmar from ghc trac, RTS uses SIGVTALRM for scheduling and profiling. And here it seems that a ldap operation takes longer than the timer, it must be interrupted by the signal. So the signal should be masked during the system call.
On the other hand, retry on EINTR sure is a common solution for the signal. But it does not work here, since the operation almost always exceeds the timer.
Hoping I described it right.

**Comment by ezyang** [comment]
Yes, GHC raises SIGVTALRMs. But the usual situation is that the operation makes partial progress, and so the "retry" is actually "please keep going".

**Comment by Magicloud** [comment]
Yes, it should be that way. But consider it is a network operation, sometimes it just takes a noticeable long time. So retry here is really not a solution. I have tried that, if I did it correct, it was a dead loop.

**Comment by ezyang** [comment]
It looks like LDAP has a RESTART option. This seems to fix it for me; can you test it on your setup:

```
diff --git a/LDAP.cabal b/LDAP.cabal
index 5ebe862..939f1d2 100644
--- a/LDAP.cabal
+++ b/LDAP.cabal
@@ -37,7 +37,7 @@ Library

   build-depends: base >= 4 && <5

-  Extra-Libraries: ldap
+  Extra-Libraries: ldap, lber

   GHC-Options: -O2
   -- CC-Options: -Iglue
@@ -53,7 +53,7 @@ Executable runtests
     Buildable: True
   else
     Buildable: False
-  Extra-Libraries: ldap
+  Extra-Libraries: ldap, lber
   Main-Is: runtests.hs
   if os(openbsd)
     CC-Options: -DLDAP_X_PROXY_AUTHZ_FAILURE=LDAP_PROXY_AUTHZ_FAILURE
diff --git a/LDAP/Init.hsc b/LDAP/Init.hsc
index 7a68259..f5a81c6 100644
--- a/LDAP/Init.hsc
+++ b/LDAP/Init.hsc
@@ -43,6 +43,11 @@ ldapSetVersion3 cld =
     with ((#{const LDAP_VERSION3})::LDAPInt) $ \copt ->
     ldap_set_option cld #{const LDAP_OPT_PROTOCOL_VERSION} (castPtr copt)

+ldapSetRestart :: LDAPPtr -> IO LDAPInt
+ldapSetRestart cld =
+    with ((#{const LDAP_OPT_ON})::LDAPInt) $ \copt ->
+    ldap_set_option cld #{const LDAP_OPT_RESTART} (castPtr copt)
+
 {- | Preferred way to initialize a LDAP connection. 
 The default port is given in 'LDAP.Constants.ldapPort'.

@@ -55,6 +60,7 @@ ldapInit host port =
        do cld <- cldap_init cs port
           rv <- fromLDAPPtr "ldapInit" (return cld)
           ldapSetVersion3 cld
+          ldapSetRestart cld
           return rv

 {- | Like 'ldapInit', but establish network connection immediately. -}
@@ -79,6 +85,7 @@ ldapInitialize uri =
     ldap <- fromLDAPPtr "ldapInitialize" (return p)
     _ <- checkLE "ldapInitialize" ldap (return r)
     ldapSetVersion3 p
+    ldapSetRestart p
     return ldap
```

**Comment by Magicloud** [comment]
Cool, let me try.

**Comment by ezyang** [comment]
Here is a version that also fixes up ldapOpen (which for some odd reason doesn't set version number)

```
diff --git a/LDAP/Init.hsc b/LDAP/Init.hsc
index 7a68259..adda047 100644
--- a/LDAP/Init.hsc
+++ b/LDAP/Init.hsc
@@ -43,6 +43,11 @@ ldapSetVersion3 cld =
     with ((#{const LDAP_VERSION3})::LDAPInt) $ \copt ->
     ldap_set_option cld #{const LDAP_OPT_PROTOCOL_VERSION} (castPtr copt)

+ldapSetRestart :: LDAPPtr -> IO LDAPInt
+ldapSetRestart cld =
+    with ((#{const LDAP_OPT_ON})::LDAPInt) $ \copt ->
+    ldap_set_option cld #{const LDAP_OPT_RESTART} (castPtr copt)
+
 {- | Preferred way to initialize a LDAP connection. 
 The default port is given in 'LDAP.Constants.ldapPort'.

@@ -55,6 +60,7 @@ ldapInit host port =
        do cld <- cldap_init cs port
           rv <- fromLDAPPtr "ldapInit" (return cld)
           ldapSetVersion3 cld
+          ldapSetRestart cld
           return rv

 {- | Like 'ldapInit', but establish network connection immediately. -}
@@ -63,7 +69,10 @@ ldapOpen :: String              -- ^ Host
             -> IO LDAP          -- ^ New LDAP Obj
 ldapOpen host port =
     withCString host (\cs ->
-                      fromLDAPPtr "ldapOpen" $ cldap_open cs port)
+        do cld <- cldap_open cs port
+           rv <- fromLDAPPtr "ldapOpen" (return cld)
+           ldapSetRestart cld
+           return rv)

 {- | Like 'ldapInit', but accepts a URI (or whitespace/comma separated
 list of URIs) which can contain a schema, a host and a port.  Besides
@@ -79,6 +88,7 @@ ldapInitialize uri =
     ldap <- fromLDAPPtr "ldapInitialize" (return p)
     _ <- checkLE "ldapInitialize" ldap (return r)
     ldapSetVersion3 p
+    ldapSetRestart p
     return ldap
```

**Comment by Magicloud** [comment]
OK. Done a testing with simplebind, it worked, on Linux, not sure of the others.

**Comment by ezyang** [comment]
OK, in that case, we'll go with that one.

**Comment by Magicloud** [comment]
Cool. In fact masking the signal is not good for RTS.
And this new one is LDAP-0.6.7?

**Comment by ezyang** [comment]
No, I need to roll up a new release (I've taken over maintenance but the websites are not yet in order yet!)

**Comment by Magicloud** [comment]
I see. Thank you for the patch.

**Pull request closed without merging**
